print("python".upper())
print("PYTHON".lower())
print("addidas".replace("d","b"))
print("Python Programlama Dili".replace(" ","/"))
print("taha".replace("ha","hta"))
print("Taha".startswith("Ta"))
print("Taha".endswith("ha"))
liste = "Recep Taha Konyar".split(" ")
print(liste)
print("                Python                ".strip())
print("                Python                ".lstrip())
print("                Python                ".rstrip())
print(">>>>>>>>>>>>>>>>python>>>>>>>>>>>>>>>>".strip(">"))
print(">>>>>>>>>>>>>>>>python>>>>>>>>>>>>>>>>".rstrip(">"))
liste = ["08","09","2002"]
liste = "/".join(liste)
print(liste)
liste1 = ["Ö","S","Y","M"]
liste1 = ".".join(liste1)
print(liste1)
print("ada kapısı yandan çarklı".count("a"))
print("ada kapısı yandan çarklı".count(" "))
print("ada kapısı yandan çarklı".count("a",3))
print("araba".find("a"))
print("araba".rfind("a"))
print("araba".find("s"))
print("araba".rfind("s"))
