open("bilgiler.txt","w")
file = open("bilgiler.txt","w")
file.close()
file = open("C:/Users/nokta/Desktop/bilgiler.txt","w")
file = open("bilgiler.txt","w",encoding ="utf-8")
file.write("recep taha konyar\n")
file.close()
file = open("bilgiler.txt","a",encoding ="utf-8")
file.write("eylül\n")
file.close()
file = open("bilgiler.txt","a",encoding ="utf-8")
file.write("merhaba\n")
file.close()
file = open("bilgiler.txt","a",encoding ="utf-8")
file.write("nasılsınız\n")
file.close()